
[loot]
	#Range: -100 ~ 100
	skill_book_mob_drop_chance_modifier = -100
	#Range: -100 ~ 100
	skill_book_chest_drop_chance_modifier = -100

[default_gamerule]
	hasFallAnimation = true
	globalStun = true
	canSwitchCombat = true
	#Allowed Values: MINING, BATTLE
	initialPlayerMode = "MINING"
	#Range: 0 ~ 100
	weightPenalty = 0
	epicDrop = false
	stiffComboAttacks = true
	noMobsInBossfight = true
	disapleEntityUI = false
	keepSkills = true
	doVanillaAttack = true

